### ISSUE TITLE
highway-shield SVG path broken on Windows

### ISSUE THREAD

**Issue by nicogodet** [maptiler/qgis-maptiler-plugin#181]
https://github.com/maptiler/qgis-maptiler-plugin/blob/1bf2803c99bc4fa200b6254180043c5959ddd921/gl2qgis/gl2qgis.py#L1546

Returns a path with mixed `\` and `/` like `'C:\Users\godet\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis-maptiler-plugin\data/icons/road_motorway.svg'`
But `\` tries to escape next character and result in a broken path `'C:?sers?odet?ppData?oaming?GIS?GIS3?rofiles?efault?ython?lugins?gis-maptiler-plugin?ata/icons/road_motorway.svg'`

**Comment by lazaa32** [comment]
Yes, I fixed this with Pathlib as well but then I run into an issue with the Bright style which was updated recently.
I will fix that next week and let you know.
Thanks!

**Comment by lazaa32** [comment]
Hi @nicogodet 
could you please test this version of the plugin? It should handle paths better both on Windows and Linux.
[qgis-maptiler-plugin.zip](https://github.com/maptiler/qgis-maptiler-plugin/files/9084015/qgis-maptiler-plugin.zip)

**Comment by nicogodet** [comment]
Tested and it does not fix the issue.
Path returns the path with backward slashes on windows (it's how windows works usually) but in QGIS expression, it needs forward slashes. That's why I used `as_posix()` in my fix.

**Comment by lazaa32** [comment]
Ok, now I understand what is the issue with Windows. I used the `as_posix()` as well. Let me know whether it works for you.
[qgis-maptiler-plugin.zip](https://github.com/maptiler/qgis-maptiler-plugin/files/9084295/qgis-maptiler-plugin.zip)

**Comment by nicogodet** [comment]
Works like a charm 😃 

(But I still have a sprite issue that I didn't report yet 
![image](https://user-images.githubusercontent.com/39594821/178287228-6f0c056d-b395-4460-abd4-432bebf5b6b4.png)
)

**Comment by lazaa32** [comment]
@nicogodet thank you very much for your help!
SVG icons path fixed in PR #182.
Regarding the sprites, the warnings you get are "false" warnings.  If a sprite is defined as an empty string `""` or `' '` it means that no sprite should be used - it is a standard way to define the property. However, QGIS tries to retrieve the empty-string sprite from sprite.json and fails, that's why it prints the warning.
There is a [filter](https://github.com/maptiler/qgis-maptiler-plugin/blob/master/browser_mapitem.py#L374) which prevents this "false" warning to be printed but only for English as I did not think of language mutations.
I will fix that and later today will release bugfix version 3.1.1 that should be available in plugin repository in a few days.
